name: CI Auto-Heal Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-heal:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests (allow failure)
      run: node node_modules/.bin/mocha --recursive --reporter spec
      continue-on-error: true

    - name: Run Auto-Healer
      run: python tools/heal.py --log logs/test.log --db healer/db.sqlite
