name: test-and-heal

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-heal:
    # Avoid duplicate runs when PR is from the same repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests and save log
        run: |
          mkdir -p logs
          npx mocha --recursive --reporter spec | tee logs/test.log || true

      - name: Run Auto-Healer
        run: |
          mkdir -p healer
          python tools/heal.py --log logs/test.log --db healer/db.sqlite

      - name: Show DB entries
        run: |
          sudo apt-get install -y sqlite3
          sqlite3 healer/db.sqlite "SELECT name FROM sqlite_master WHERE type='table';"
          sqlite3 healer/db.sqlite "SELECT * FROM fixes;" || true

      - name: Upload logs and DB
        uses: actions/upload-artifact@v4
        with:
          name: healer-artifacts
          path: |
            logs/test.log
            healer/db.sqlite
